
#define MOTORLA   REGISTER_BIT(PORTC,7)
#define MOTORLB   REGISTER_BIT(PORTC,6)
#define PWML      OCR1A

#define MOTORBA   REGISTER_BIT(PORTC,2)
#define MOTORBB   REGISTER_BIT(PORTC,3)
#define PWMB      OCR1B

#define MOTORRA   REGISTER_BIT(PORTC,4)
#define MOTORRB   REGISTER_BIT(PORTC,5)
#define PWMR      OCR3A

#define MOTORFA   REGISTER_BIT(PORTC,0)
#define MOTORFB   REGISTER_BIT(PORTC,1)
#define PWMF      OCR3B

#define LinA      REGISTER_BIT(PORTD,0)
#define LinB      REGISTER_BIT(PORTD,1)
#define LinPWM 	  REGISTER_BIT(PORTB,4)

#define LBPHASE    REGISTER_BIT(PORTE,4) 
#define RBPHASE    REGISTER_BIT(PORTE,5)
